const STYLE_ID = 'dsh-org-panel-cy9'

export const CY9_CSS = String.raw`
.cy9-native-composer-hidden{display:none!important}
.cy9.cy9{
  --bg:#050914;--panel:#09111f;--panel2:#0d1727;--panel3:#111d31;--line:rgba(133,159,202,.17);
  --text:#edf4ff;--muted:#8c9bb5;--dim:#586780;--cyan:#43d9ff;--blue:#5e8dff;--violet:#a36bff;
  --green:#4de2a1;--amber:#f0b55e;--red:#ff6f86;--r:10px;
  box-sizing:border-box;width:100%;height:calc(100dvh - 112px)!important;min-height:680px;overflow:hidden;
  display:flex;flex-direction:column;background:radial-gradient(circle at 62% -20%,rgba(90,68,180,.16),transparent 42%),var(--bg);
  color:var(--text);font:13px/1.45 Inter,"Segoe UI","PingFang SC",sans-serif;letter-spacing:.01em;
}
.cy9 *{box-sizing:border-box}.cy9 button,.cy9 textarea{font:inherit}.cy9 button{color:inherit}.cy9 button:focus-visible,.cy9 textarea:focus-visible{outline:2px solid var(--cyan);outline-offset:2px}
.cy9 *{scrollbar-width:thin;scrollbar-color:#31415d transparent}.cy9 *::-webkit-scrollbar{width:6px;height:6px}.cy9 *::-webkit-scrollbar-track{background:transparent}.cy9 *::-webkit-scrollbar-thumb{border-radius:8px;background:#31415d}.cy9 *::-webkit-scrollbar-thumb:hover{background:#476180}
.cy9 img{display:block}.cy9 .cy9-asset-fallback{display:grid;place-items:center;background:linear-gradient(145deg,#1d2c45,#101725);color:#dff8ff;font-weight:800}
.cy9 img.is-loading{opacity:.25}.cy9 img.is-loaded{opacity:1;transition:opacity .18s ease}
.cy9-header{height:58px;flex:0 0 58px;display:grid;grid-template-columns:minmax(250px,1fr) auto minmax(260px,1fr);align-items:center;gap:18px;padding:0 16px;border-bottom:1px solid var(--line);background:rgba(5,9,20,.94);backdrop-filter:blur(16px)}
.cy9-brand{min-width:0;display:flex;align-items:center;gap:10px}.cy9-brand>img,.cy9-brand>.cy9-asset-fallback{width:38px;height:38px;border-radius:9px;border:1px solid rgba(67,217,255,.38);box-shadow:0 0 24px rgba(67,217,255,.12)}
.cy9-brand-kicker{color:var(--cyan);font:700 9px/1.2 ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:.18em}.cy9-brand-title{font-size:17px;font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cy9-brand-title em{font-style:normal;color:#b8c4d9;font-weight:500}
.cy9-stats{display:flex;height:36px;border:1px solid var(--line);border-radius:8px;overflow:hidden;background:rgba(14,24,42,.58)}.cy9-stat{min-width:70px;padding:4px 10px;text-align:center;border-left:1px solid var(--line)}.cy9-stat:first-child{border-left:0}.cy9-stat b{display:block;font:800 13px/1.05 ui-monospace,Consolas,monospace}.cy9-stat span{display:block;margin-top:3px;color:var(--muted);font-size:9px}.cy9-stat.hot b{color:var(--green)}.cy9-stat.warn b{color:var(--red)}
.cy9-header-right{display:flex;align-items:center;justify-content:flex-end;gap:10px}.cy9-clock{text-align:right}.cy9-clock b{display:block;font:700 13px/1.1 ui-monospace,Consolas,monospace}.cy9-clock span{color:var(--green);font-size:9px}.cy9-market-btn{height:32px;padding:0 12px;border:1px solid rgba(163,107,255,.35);border-radius:7px;background:rgba(123,74,210,.13);cursor:pointer}.cy9-market-btn:hover{border-color:var(--violet);background:rgba(123,74,210,.22)}
.cy9-boss{display:flex;align-items:center;gap:7px}.cy9-boss-avatar{width:30px;height:30px;display:grid;place-items:center;border-radius:8px;background:linear-gradient(145deg,#5d35a5,#1a3860);font-weight:900}.cy9-boss-name{font-weight:700}.cy9-boss-name small{display:block;color:var(--muted);font-size:9px;font-weight:400}
.cy9-body{min-height:0;flex:1;display:grid;grid-template-columns:250px minmax(720px,1fr) 300px;gap:10px;padding:10px;overflow:hidden}.cy9-left-wrap{display:contents}
.cy9-left{min-width:0;min-height:0;display:flex;flex-direction:column;border:1px solid var(--line);border-radius:var(--r);background:rgba(9,17,31,.9);overflow:hidden}.cy9-left-head{height:50px;flex:0 0 50px;padding:10px 12px;border-bottom:1px solid var(--line)}.cy9-left-head b{display:block;font-size:14px}.cy9-left-head span{color:var(--muted);font-size:10px}
.cy9-left-filters{display:flex;gap:4px;padding:8px;border-bottom:1px solid var(--line);overflow-x:auto;scrollbar-width:none}.cy9-left-filters::-webkit-scrollbar{display:none}.cy9-left-filters button{height:25px;padding:0 8px;border:1px solid transparent;border-radius:6px;background:transparent;color:var(--muted);white-space:nowrap;cursor:pointer}.cy9-left-filters button.on{border-color:rgba(67,217,255,.4);background:rgba(67,217,255,.1);color:#dff9ff}
.cy9-left-list{min-height:0;overflow:auto;padding:4px 7px 12px}.cy9-department{margin-top:7px}.cy9-department-title{display:flex;justify-content:space-between;padding:5px 6px;color:#aebbd0;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.08em}.cy9-department-title span{color:var(--dim)}
.cy9-emp{width:100%;min-height:56px;display:grid;grid-template-columns:42px minmax(0,1fr);gap:9px;align-items:center;padding:6px;border:1px solid transparent;border-radius:8px;background:transparent;text-align:left;cursor:pointer}.cy9-emp:hover{background:rgba(255,255,255,.035)}.cy9-emp.active{border-color:rgba(67,217,255,.45);background:linear-gradient(90deg,rgba(67,217,255,.13),rgba(163,107,255,.06));box-shadow:inset 3px 0 0 var(--cyan)}
.cy9-emp-avatar{width:42px;height:42px;border-radius:9px;overflow:hidden;background:#111c2f}.cy9-emp-avatar img,.cy9-emp-avatar .cy9-asset-fallback{width:100%;height:100%;object-fit:cover}.cy9-emp-copy{min-width:0}.cy9-emp-line{display:flex;align-items:baseline;gap:6px;min-width:0}.cy9-emp-name{font-weight:800;white-space:nowrap}.cy9-emp-role{min-width:0;color:var(--muted);font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cy9-emp-task{margin-top:3px;color:var(--muted);font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cy9-emp-task i{display:inline-block;width:6px;height:6px;margin-right:5px;border-radius:50%;background:#657087}.cy9-emp-task i.running{background:var(--cyan);box-shadow:0 0 8px var(--cyan)}.cy9-emp-task i.done{background:var(--green)}.cy9-emp-task i.wait{background:var(--red)}
.cy9-center{min-width:0;min-height:0;display:flex;flex-direction:column;gap:10px;overflow:hidden}.cy9-office-shell{min-height:0;flex:1;display:flex;flex-direction:column;border:1px solid rgba(67,217,255,.25);border-radius:var(--r);overflow:hidden;background:#050a14;box-shadow:0 18px 60px rgba(0,0,0,.2)}
.cy9-office-head{height:42px;flex:0 0 42px;display:flex;align-items:center;gap:14px;padding:0 12px;border-bottom:1px solid var(--line);background:linear-gradient(90deg,rgba(20,33,55,.95),rgba(9,16,29,.95))}.cy9-office-head>div:first-child{display:flex;align-items:baseline;gap:9px;margin-right:auto}.cy9-office-head b{font-size:13px}.cy9-office-head span{color:var(--muted);font-size:10px}.cy9-office-legend{display:flex;gap:9px}.cy9-office-legend span:before{content:"";display:inline-block;width:6px;height:6px;margin-right:4px;border-radius:50%}.cy9-office-legend .working:before{background:var(--cyan)}.cy9-office-legend .meeting:before{background:var(--violet)}.cy9-office-legend .blocked:before{background:var(--red)}
.cy9-office-toolbar{display:flex;gap:3px}.cy9-office-toolbar button{height:24px;padding:0 7px;border:1px solid var(--line);border-radius:5px;background:rgba(255,255,255,.03);color:var(--muted);font-size:9px;cursor:pointer}.cy9-office-toolbar button.on{border-color:rgba(67,217,255,.55);color:var(--cyan);background:rgba(67,217,255,.1)}
.cy9-office-viewport{min-height:0;flex:1;overflow:auto;background:#030711}.cy9-office-scroll{position:relative;min-width:100%;min-height:100%}.cy9-office-world{position:absolute;left:0;top:0;width:1200px;height:720px;transform-origin:0 0;background-size:1200px 720px;background-position:center;background-repeat:no-repeat;overflow:hidden}.cy9-office-world.no-asset{background:radial-gradient(circle at 65% 20%,rgba(87,64,171,.32),transparent 30%),linear-gradient(145deg,#0b1a2c,#050913 65%)}
.cy9-zone-hotspot{position:absolute;border:1px solid transparent;border-radius:16px;transition:border-color .2s,background .2s;pointer-events:none}.cy9-zone-hotspot>span{position:absolute;left:10px;top:8px;padding:4px 7px;border:1px solid rgba(114,185,255,.18);border-radius:5px;background:rgba(3,9,20,.74);color:#b8cbe5;font-size:9px;letter-spacing:.08em}.cy9-zone-hotspot.meeting-glow{border-color:rgba(163,107,255,.7);background:rgba(163,107,255,.07);box-shadow:inset 0 0 40px rgba(163,107,255,.14),0 0 20px rgba(163,107,255,.2)}
.cy9-sprite{position:absolute;z-index:8;width:78px;height:104px;padding:0;border:0;background:transparent;cursor:pointer;transform:translate(-50%,-70%);transition:left 1.6s cubic-bezier(.2,.75,.25,1),top 1.6s cubic-bezier(.2,.75,.25,1),filter .2s}.cy9-sprite:hover,.cy9-sprite.active{z-index:20;filter:drop-shadow(0 0 10px rgba(67,217,255,.75))}.cy9-sprite.active:after{content:"";position:absolute;inset:12px 4px 22px;border:1px solid var(--cyan);border-radius:50%;box-shadow:0 0 18px rgba(67,217,255,.45)}
.cy9-sprite-img{position:relative;display:block;width:74px;height:74px;margin:auto}.cy9-sprite-img img,.cy9-sprite-img>.cy9-asset-fallback{position:relative;z-index:2;width:100%;height:100%;object-fit:contain;filter:drop-shadow(0 5px 5px rgba(0,0,0,.65))}.cy9-sprite-badge{position:absolute;right:-4px;top:0;z-index:4;min-width:20px;height:20px;padding:0 4px;display:grid;place-items:center;border:1px solid rgba(255,255,255,.55);border-radius:10px;background:#131a2a;color:#fff;font:900 9px/20px ui-monospace,Consolas,monospace}.cy9-sprite.blocked .cy9-sprite-badge{background:var(--red)}.cy9-sprite.done .cy9-sprite-badge{background:#14895e}.cy9-sprite.thinking .cy9-sprite-badge{background:#623ea8}.cy9-monitor-glow{position:absolute;left:13px;bottom:5px;z-index:1;width:48px;height:24px;border-radius:50%;background:rgba(67,217,255,.4);filter:blur(11px);animation:cy9-pulse 1.8s infinite}
.cy9-sprite-label{position:relative;z-index:3;display:inline-flex;max-width:96px;flex-direction:column;align-items:center;padding:2px 6px;border:1px solid rgba(98,131,179,.3);border-radius:5px;background:rgba(3,8,18,.88);white-space:nowrap}.cy9-sprite-label b{font-size:10px}.cy9-sprite-label small{max-width:84px;color:#9eafc7;font-size:8px;overflow:hidden;text-overflow:ellipsis}.cy9-sprite-card{position:absolute;left:84px;top:4px;width:210px;display:none;padding:10px;border:1px solid rgba(67,217,255,.32);border-radius:8px;background:rgba(5,11,23,.97);text-align:left;box-shadow:0 16px 36px rgba(0,0,0,.5)}.cy9-sprite:hover .cy9-sprite-card,.cy9-sprite:focus-visible .cy9-sprite-card{display:grid;gap:5px}.cy9-sprite-card em{color:var(--cyan);font-size:10px}.cy9-sprite-card>span{color:var(--muted);font-size:10px}.cy9-sprite-actions{display:flex!important;gap:6px;margin-top:4px}.cy9-sprite-actions span{padding:4px 7px;border:1px solid var(--line);border-radius:5px;color:#dce8f8;cursor:pointer}
.cy9-collab{position:relative;flex:0 0 auto;min-height:40px;border:1px solid var(--line);border-radius:var(--r);overflow:hidden;background:rgba(8,15,28,.96)}.cy9-collab-grip{position:absolute;left:0;right:0;top:0;height:5px;z-index:8;cursor:ns-resize}.cy9-collab-grip:after{content:"";position:absolute;left:50%;top:1px;width:48px;height:2px;border-radius:2px;background:rgba(133,159,202,.26)}.cy9-collab-head{height:40px;display:flex;align-items:center;gap:9px;padding:0 10px;border-bottom:1px solid var(--line);background:#0c1525}.cy9-collab-head>div{display:flex;align-items:baseline;gap:8px}.cy9-collab-head span{color:var(--muted);font-size:10px}.cy9-collab-toggle,.cy9-filter-chip{height:25px;padding:0 8px;border:1px solid var(--line);border-radius:5px;background:transparent;color:var(--muted);cursor:pointer}.cy9-collab-toggle{margin-left:auto}.cy9-filter-chip{color:var(--cyan);border-color:rgba(67,217,255,.3)}.cy9-error{color:var(--red)!important}
.cy9-collab-body{height:calc(100% - 40px);display:grid;grid-template-columns:150px minmax(0,1fr);min-height:0}.cy9-collab-body.with-thread{grid-template-columns:150px minmax(0,1fr) 260px}.cy9-channels{min-height:0;padding:8px;border-right:1px solid var(--line);overflow:auto;background:rgba(5,10,19,.65)}.cy9-channels-label{padding:2px 6px 7px;color:var(--dim);font-size:9px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.cy9-channel{width:100%;height:27px;display:grid;grid-template-columns:16px 1fr auto;align-items:center;gap:3px;padding:0 6px;border:0;border-radius:5px;background:transparent;color:var(--muted);font-size:10px;text-align:left;cursor:pointer}.cy9-channel:hover{background:rgba(255,255,255,.035)}.cy9-channel.on{background:rgba(67,217,255,.1);color:#e5fbff}.cy9-channel i{font-style:normal;color:var(--dim)}.cy9-channel em{font-style:normal;color:var(--dim);font-size:9px}
.cy9-chat{min-width:0;min-height:0;display:grid;grid-template-rows:minmax(0,1fr) 60px}.cy9-chat-body{min-height:0;overflow:auto;padding:10px 13px}.cy9-chat-empty{max-width:560px;margin:24px auto;padding:18px;border:1px dashed rgba(99,142,197,.24);border-radius:9px;color:var(--muted);text-align:center}.cy9-msg{display:grid;grid-template-columns:34px minmax(0,1fr);gap:9px;margin:0 0 10px}.cy9-msg-avatar{width:34px;height:34px;border-radius:8px;overflow:hidden;background:#131f34}.cy9-msg-avatar img,.cy9-msg-avatar .cy9-asset-fallback{width:100%;height:100%;object-fit:cover}.cy9-msg-avatar.boss{display:grid;place-items:center;background:linear-gradient(145deg,#5b33a0,#1a3b65);font-weight:900}.cy9-msg-main{min-width:0}.cy9-msg-meta{display:flex;gap:7px;align-items:baseline;margin-bottom:3px}.cy9-msg-meta b{font-size:11px}.cy9-msg-meta span{color:var(--cyan);font-size:9px}.cy9-msg-meta em{margin-left:auto;color:var(--dim);font-size:9px;font-style:normal}.cy9-msg-bubble{display:inline-block;max-width:min(780px,94%);padding:7px 9px;border:1px solid rgba(112,141,184,.16);border-radius:3px 9px 9px 9px;background:#101a2b;color:#dbe6f6;white-space:pre-wrap;word-break:break-word}.cy9-msg.from-boss{grid-template-columns:minmax(0,1fr) 34px}.cy9-msg.from-boss .cy9-msg-avatar{grid-column:2}.cy9-msg.from-boss .cy9-msg-main{grid-column:1;grid-row:1;text-align:right}.cy9-msg.from-boss .cy9-msg-bubble{border-radius:9px 3px 9px 9px;border-color:rgba(163,107,255,.25);background:#17142a;text-align:left}.cy9-msg-thinking{margin-top:4px;color:var(--muted);font-size:9px}.cy9-msg-thinking summary{cursor:pointer}.cy9-msg-thinking p{margin:4px 0;padding:6px 8px;border-left:2px solid rgba(163,107,255,.5);background:rgba(163,107,255,.05)}
.cy9-msg-divider{display:flex;align-items:center;gap:8px;margin:10px 0;color:#8ea3c2;font-size:9px;text-transform:uppercase;letter-spacing:.08em}.cy9-msg-divider span{height:1px;flex:1;background:var(--line)}.cy9-msg-tool{width:100%;display:grid;grid-template-columns:34px minmax(0,1fr);gap:8px;margin:7px 0;padding:7px;border:1px solid rgba(67,217,255,.18);border-radius:7px;background:rgba(67,217,255,.045);text-align:left;cursor:pointer}.cy9-msg-tool-icon{width:34px;height:30px;display:grid;place-items:center;border-radius:6px;background:rgba(67,217,255,.12);color:var(--cyan);font:800 8px ui-monospace,Consolas,monospace}.cy9-msg-tool-main{min-width:0;display:grid}.cy9-msg-tool-main b{font:700 10px ui-monospace,Consolas,monospace}.cy9-msg-tool-main b em{float:right;color:var(--dim);font-style:normal;font-weight:400}.cy9-msg-tool-main>span{color:var(--muted);font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cy9-msg-tool.running{animation:cy9-border 1.8s infinite}
.cy9-msg-typing{display:flex;align-items:center;gap:7px;color:var(--muted);font-size:10px}.cy9-msg-typing>img,.cy9-msg-typing>.cy9-asset-fallback{width:24px;height:24px;border-radius:6px;object-fit:cover}.cy9-msg-typing>span{display:flex;gap:3px}.cy9-msg-typing i{width:4px;height:4px;border-radius:50%;background:var(--cyan);animation:cy9-dot 1.1s infinite}.cy9-msg-typing i:nth-child(2){animation-delay:.16s}.cy9-msg-typing i:nth-child(3){animation-delay:.32s}
.cy9-chat-input{position:relative;display:grid;grid-template-columns:minmax(0,1fr) 62px;grid-template-rows:36px 14px;gap:2px 8px;padding:7px 9px;border-top:1px solid var(--line);background:#0b1322}.cy9-chat-input textarea{grid-row:1/3;resize:none;padding:8px 10px;border:1px solid rgba(110,140,183,.25);border-radius:7px;background:#070d18;color:var(--text);outline:0}.cy9-chat-input textarea:focus{border-color:rgba(67,217,255,.55);box-shadow:0 0 0 2px rgba(67,217,255,.08)}.cy9-chat-input>span{color:var(--dim);font-size:8px}.cy9-chat-send{grid-column:2;grid-row:1/3;border:0;border-radius:7px;background:linear-gradient(145deg,#4778df,#6b43be);font-weight:800;cursor:pointer}.cy9-chat-send:disabled{opacity:.35;cursor:not-allowed}.cy9-mention-pop{position:absolute;left:9px;bottom:59px;z-index:30;width:300px;max-height:270px;padding:5px;border:1px solid rgba(67,217,255,.3);border-radius:9px;background:#0b1424;box-shadow:0 18px 44px rgba(0,0,0,.55);overflow:auto}.cy9-mention-pop button{width:100%;display:grid;grid-template-columns:30px auto 1fr;align-items:center;gap:8px;padding:5px;border:0;border-radius:6px;background:transparent;text-align:left;cursor:pointer}.cy9-mention-pop button.on{background:rgba(67,217,255,.11)}.cy9-mention-pop img,.cy9-mention-pop .cy9-asset-fallback{width:30px;height:30px;border-radius:6px;object-fit:cover}.cy9-mention-pop span{color:var(--muted);font-size:10px}
.cy9-thread{min-width:0;border-left:1px solid var(--line);background:#09111f}.cy9-thread-head{height:36px;display:flex;align-items:center;justify-content:space-between;padding:0 9px;border-bottom:1px solid var(--line)}.cy9-thread-head button{border:0;background:transparent;color:var(--muted);cursor:pointer}.cy9-thread-body{padding:10px;overflow:auto}.cy9-thread-body>span{color:var(--muted);font-size:9px}.cy9-thread-body p{white-space:pre-wrap;word-break:break-word}.cy9-thread-safe{padding:8px;border-left:2px solid var(--violet);background:rgba(163,107,255,.06);color:var(--muted);font-size:9px}
.cy9-rail{min-width:0;min-height:0;display:flex;flex-direction:column;gap:10px;overflow:auto}.cy9-card{border:1px solid var(--line);border-radius:var(--r);background:rgba(9,17,31,.9);overflow:hidden}.cy9-card-head{height:38px;display:flex;align-items:center;gap:7px;padding:0 10px;border-bottom:1px solid var(--line)}.cy9-card-head b{margin-right:auto;font-size:12px}.cy9-card-head span{color:var(--muted);font-size:8px;letter-spacing:.1em}.cy9-card-head span.live{color:var(--green)}.cy9-card-head button{border:0;background:transparent;color:var(--muted);font-size:9px;cursor:pointer}
.cy9-status-grid{display:grid;grid-template-columns:repeat(4,1fr);padding:8px}.cy9-status-grid>div{text-align:center;border-left:1px solid var(--line)}.cy9-status-grid>div:first-child{border-left:0}.cy9-status-grid b{display:block;font:800 13px ui-monospace,Consolas,monospace}.cy9-status-grid span{color:var(--muted);font-size:8px}.cy9-session-line{margin:0 8px 8px;padding:7px;border-radius:6px;background:rgba(255,255,255,.025);color:var(--muted);font-size:9px}.cy9-session-line i{display:inline-block;width:6px;height:6px;margin-right:6px;border-radius:50%;background:#667085}.cy9-session-line.live i{background:var(--green);box-shadow:0 0 8px var(--green)}
.cy9-task-card{flex:0 0 auto}.cy9-taskflow-row{display:grid;grid-template-columns:30px minmax(0,1fr) auto;gap:7px;align-items:center;padding:8px;border-top:1px solid rgba(133,159,202,.09)}.cy9-taskflow-avatar{width:30px;height:30px;border-radius:6px;overflow:hidden}.cy9-taskflow-avatar img,.cy9-taskflow-avatar .cy9-asset-fallback{width:100%;height:100%;object-fit:cover}.cy9-taskflow-main{min-width:0}.cy9-taskflow-main b,.cy9-taskflow-main span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cy9-taskflow-main b{font-size:10px}.cy9-taskflow-main span{color:var(--muted);font-size:8px}.cy9-taskflow-state{padding:2px 5px;border-radius:4px;background:rgba(96,116,149,.14);color:var(--muted);font-size:8px}.cy9-taskflow-state.running{color:var(--cyan)}.cy9-taskflow-state.done{color:var(--green)}.cy9-taskflow-state.wait{color:var(--red)}
.cy9-insight-card{min-height:180px;flex:1;overflow:auto}.cy9-rail-tabs{position:sticky;top:0;z-index:2;display:grid;grid-template-columns:repeat(3,1fr);padding:6px;border-bottom:1px solid var(--line);background:#0b1423}.cy9-rail-tabs button{height:27px;border:0;border-radius:5px;background:transparent;color:var(--muted);cursor:pointer}.cy9-rail-tabs button.on{background:rgba(163,107,255,.13);color:#efe7ff}.cy9-empty{padding:16px 12px;color:var(--muted);font-size:9px;text-align:center}.cy9-feed-row{display:grid;grid-template-columns:32px minmax(0,1fr);gap:8px;padding:9px;border-bottom:1px solid rgba(133,159,202,.09)}.cy9-feed-row>img,.cy9-feed-row>.cy9-asset-fallback{width:32px;height:32px;border-radius:6px;object-fit:cover}.cy9-feed-row em{float:right;color:var(--dim);font-size:8px;font-style:normal}.cy9-feed-row b{font-size:10px}.cy9-feed-row p{margin:2px 0;color:var(--muted);font-size:9px}.cy9-skill-row,.cy9-plugin-row{display:grid;gap:4px;padding:9px;border-bottom:1px solid rgba(133,159,202,.09)}.cy9-skill-row b,.cy9-plugin-row b{font-size:10px}.cy9-skill-row span,.cy9-plugin-row span{color:var(--muted);font-size:9px}.cy9-skill-row>div{height:3px;background:rgba(255,255,255,.05)}.cy9-skill-row i{display:block;width:100%;height:100%;background:var(--violet)}.cy9-skill-row i.indet{width:35%;animation:cy9-slide 1.5s infinite}.cy9-plugin-row button,.cy9-card-action{justify-self:start;padding:5px 8px;border:1px solid rgba(163,107,255,.3);border-radius:5px;background:rgba(163,107,255,.08);font-size:9px;cursor:pointer}.cy9-card-action{margin:9px}
.cy9-rail-toggle,.cy9-staff-toggle{display:none;position:fixed;z-index:90;right:14px;bottom:14px;height:34px;padding:0 11px;border:1px solid rgba(67,217,255,.45);border-radius:8px;background:#0d1a2d;color:var(--cyan);box-shadow:0 12px 30px rgba(0,0,0,.4);cursor:pointer}.cy9-staff-toggle{left:14px;right:auto}
.cy9-profile-overlay{position:fixed;inset:0;z-index:200;display:grid;place-items:center;padding:20px;background:rgba(1,4,10,.74);backdrop-filter:blur(8px)}.cy9-profile{position:relative;width:min(620px,95vw);max-height:86vh;padding:18px;border:1px solid rgba(67,217,255,.3);border-radius:12px;background:#0a1323;box-shadow:0 30px 90px rgba(0,0,0,.7);overflow:auto}.cy9-profile-close{position:absolute;right:12px;top:12px;border:0;background:transparent;color:var(--muted);cursor:pointer}.cy9-profile-head{display:grid;grid-template-columns:150px 1fr;gap:18px;align-items:center}.cy9-profile-head>img,.cy9-profile-head>.cy9-asset-fallback{width:150px;height:150px;border-radius:12px;object-fit:contain;background:#07101e}.cy9-profile-head b{display:block;font-size:24px}.cy9-profile-head span{color:var(--cyan)}.cy9-profile-head p{color:var(--muted)}.cy9-profile-section{margin-top:14px}.cy9-profile-section label{display:block;margin-bottom:6px;color:var(--muted);font-size:10px}.cy9-profile-chips{display:flex;flex-wrap:wrap;gap:6px}.cy9-profile-chips span{padding:5px 7px;border:1px solid var(--line);border-radius:6px;background:rgba(255,255,255,.025);font-size:10px}.cy9-profile-chips .mono{font-family:ui-monospace,Consolas,monospace}.cy9-profile-actions{display:flex;gap:8px;margin-top:16px}.cy9-profile-actions button{padding:8px 12px;border:1px solid rgba(67,217,255,.3);border-radius:7px;background:rgba(67,217,255,.07);cursor:pointer}
@media(max-width:1580px){.cy9-body{grid-template-columns:220px minmax(660px,1fr) 270px}.cy9-brand-title em{display:none}.cy9-stat{min-width:61px;padding-inline:7px}.cy9-clock{display:none}.cy9-collab-body{grid-template-columns:132px minmax(0,1fr)}.cy9-collab-body.with-thread{grid-template-columns:132px minmax(0,1fr) 240px}}
@media(max-width:1360px){.cy9-body{grid-template-columns:220px minmax(0,1fr)}.cy9-rail{position:fixed;z-index:80;top:118px;right:10px;bottom:10px;width:290px;padding:0;transform:translateX(110%);transition:none}.cy9.cy9 .cy9-rail.open{transform:translateX(0)!important}.cy9-rail-toggle{display:block}.cy9-stats .cy9-stat:first-child{display:none}.cy9-header{grid-template-columns:minmax(220px,1fr) auto auto}}
@media(max-width:1000px){.cy9-header{grid-template-columns:1fr auto}.cy9-stats{display:none}.cy9-boss{display:none}.cy9-body{grid-template-columns:minmax(0,1fr);padding:8px}.cy9-left-wrap{position:fixed;z-index:85;left:8px;top:118px;bottom:8px;width:232px;display:block;transform:translateX(-110%);transition:none}.cy9.cy9 .cy9-left-wrap.open{transform:translateX(0)!important}.cy9-left-wrap .cy9-left{height:100%}.cy9-staff-toggle{display:block}.cy9-office-world{transform-origin:0 0}.cy9-collab-body.with-thread{grid-template-columns:120px minmax(0,1fr)}.cy9-thread{position:absolute;right:0;top:40px;bottom:0;width:250px;z-index:20;box-shadow:-18px 0 40px rgba(0,0,0,.42)}.cy9-profile-head{grid-template-columns:110px 1fr}.cy9-profile-head>img,.cy9-profile-head>.cy9-asset-fallback{width:110px;height:110px}}
@media(max-width:720px){.cy9{min-height:620px}.cy9-header-right .cy9-market-btn{display:none}.cy9-body{padding:6px}.cy9-office-head{padding-inline:8px}.cy9-office-legend{display:none}.cy9-collab-body{grid-template-columns:108px minmax(0,1fr)}.cy9-msg-bubble{max-width:100%}.cy9-profile-head{grid-template-columns:1fr}.cy9-profile-head>img,.cy9-profile-head>.cy9-asset-fallback{margin:auto}}
@media(prefers-reduced-motion:reduce){.cy9 *{scroll-behavior:auto!important;animation:none!important;transition:none!important}}
@keyframes cy9-pulse{0%,100%{opacity:.35}50%{opacity:1}}@keyframes cy9-dot{0%,100%{opacity:.25;transform:translateY(0)}50%{opacity:1;transform:translateY(-2px)}}@keyframes cy9-border{0%,100%{border-color:rgba(67,217,255,.18)}50%{border-color:rgba(67,217,255,.55)}}@keyframes cy9-slide{from{transform:translateX(-20%)}to{transform:translateX(210%)}}
`

export function installStyles() {
  if (typeof document === 'undefined' || document.getElementById(STYLE_ID)) return
  const style = document.createElement('style')
  style.id = STYLE_ID
  style.textContent = CY9_CSS
  document.head.appendChild(style)
}
